# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pjuu Blog 
email: hello@pjuu.com
description: > # this means to ignore newlines until "baseurl:"
  The pjuu.com blog. Everything from architecture and engineering to design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.pjuu.com" # the base hostname & protocol for your site
main_url: "https://pjuu.com/"
github_username:  pjuu

# Build settings
markdown: kramdown
